### ISSUE TITLE
Bestehende Buchungen nicht über Kalender änderbar + Bugs in yForm-Tabelle

### ISSUE THREAD

**Issue by iceman-fx** [dtpop/buchungskalender#5]
Leider kann man aktuell bestehende Buchungen nicht über den Kalender ändern und muss diese mühsam über die yForm-Tabelle suchen und editieren.
Hier wäre ein Link zum entsprechenden Objekt in der yForm-Tabelle sinnvoll, um gleich ins Editierformular zu springen.

Bugs:
In der yForm-Tabelle für die vorhanden Buchungen sind einige Fehler drin.
1. das Feld Objekt ist nicht ausgefüllt, wenn man einen Eintrag über den Kalender angelegt und jetzt editieren möchte.
2. ich kann dort ungewollte Überschneidungen von Buchungen vornehmen

![Unbenannt](https://user-images.githubusercontent.com/4291047/119451487-9c696000-bd35-11eb-9281-1099a5f08fbc.PNG)

**Comment by dtpop** [comment]
Shift + Klick im Kalender führt zum Datensatz.
Im Backend kann man tatsächlich Überschneidungen eintragen, hier findet keine Überprüfung statt.

**Comment by iceman-fx** [comment]
Shift+Klick geht, wenn man dies weiß.
Vielleicht sollte hier in der Kalenderübersicht dazu oben eine Info stehen.

besser wäre natürlich immer noch ein simpler Klick in den roten Bereich (Buchung), um zum Datensatz zu gelangen.

**Comment by iceman-fx** [comment]
Die Überschneidungen sind leider immer noch durchführbar.
Das wird mit Sicherheit zu Problemen bei manch Kunden führen.

Evtl. wäre es besser, auf eigene Tabellen anstatt auf yForm zu setzen, falls solch eine Prüfung in yForm nicht realisierbar ist.
